name: Task 12

on:
  workflow_dispatch:
    inputs:
      skip_run:
        type: boolean
        default: false
  schedule:
    - cron: '*/5 * * * *'

jobs:
  kill-switch:
    runs-on: ubuntu-latest
    steps:
      - name: main logic
        if: (github.event_name == 'workflow_dispatch' && inputs.skip_run == 'false') || github.event_name == 'schedule'
        run: echo "Main Job executed"
      - name: Run Skipped
        if: inputs.skip_run == 'true'
        run: echo "Run Skipped"