name: Task 4

on:
  push:
    branches:
      - main

jobs:
  detect-changes:
    runs-on: ubuntu-latest

    outputs:
      frontend: ${{ steps.detect.outputs.frontend }}
      backend: ${{ steps.detect.outputs.backend }}

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Detection
        shell: bash
        id: detect
        run: |
          if git diff --name-only HEAD^ HEAD | grep '^frontend/'
          then
            echo "frontend=true" >> $GITHUB_OUTPUT
          else
            echo "frontend=false" >> $GITHUB_OUTPUT
          fi

          if git diff --name-only HEAD^ HEAD | grep '^backend/'
          then 
            echo "backend=true" >> $GITHUB_OUTPUT
          else
            echo "backend=false" >> $GITHUB_OUTPUT
          fi

  frontend-job:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.frontend == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Output
        run: echo "Frontend Job"
  
  backend-job:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.backend == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Output
        run: echo "Backend Job"
